# The version of the docker-compose.
version: "3.8"
# Telling docker-compose to build the client and server images and run them in containers.
services:
  client:
    # Telling docker-compose to build the client image using the Dockerfile in the client directory.
    build: ./client
    # Giving the container a name.
    container_name: clientapp_c
    # Mapping the port 3000 on the host machine to the port 3000 on the container.
    ports:
      - "5173:5173"
    # Allows you to run container in detached mode.
    stdin_open: true
    tty: true
  server:
    # Telling docker-compose to build the client image using the Dockerfile in the server directory.
    build: ./server
    container_name: serverapp_c
    ports:
      - "3001:3001"
    environment:
      GMAIL_USERNAME: ttlabsofficial@gmail.com
      GMAIL_PASSWORD: qlbr ifyh nzny hnzj
      MONGO_URL: mongodb://mongo:27017/TTLABS_DB
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" # Map MongoDB port to host
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
