export const data = [
  {
    _id: "v436djghdvaodvhdvi",
    subject_name: "Object Oriented Software Engineering",
    subject_code: "COMP2003",
    session_type: "Lecture",
    duration: "2",
    lecture_hall: "LT 105",
    lect_name: "Mr. Kasun Madhushanka",
    day: { _id: "addvadva", index: 1, name: "Monday" },
    start_time: { _id: "dguwod45zsz", index: 1, name: "08:30" },
  },
  {
    _id: "v436lbsdvaodvhdvi",
    subject_name: "Object Oriented Software Engineering",
    subject_code: "COMP2003",
    session_type: "Lecture",
    duration: "2",
    lecture_hall: "LT 105",
    lect_name: "Mr. Kasun Madhushanka",
    day: { _id: "fbdsfb4", index: 2, name: "Tuesday" },
    start_time: { _id: "dguwod45zsz", index: 1, name: "08:30" },
  },
  {
    _id: "go64577dgpwoudg",
    subject_name: "Human Computer Interface",
    subject_code: "ISTE3002",
    session_type: "Lab",
    duration: "2",
    lecture_hall: "LT 105",
    lect_name: "Ms. Divya Nanayakkara",
    day: { _id: "fbdsfb4", index: 2, name: "Tuesday" },
    start_time: { _id: "xvzxxvzveg2", index: 3, name: "10:30" },
  },
  {
    _id: "235BSDPBNKFWwon",
    subject_name: "Operating Systems",
    subject_code: "COMP2006",
    session_type: "Lab",
    duration: "2",
    lecture_hall: "LT 105",
    lect_name: "Mr. Praveen Gamage",
    day: { _id: "fbdsfb4", index: 2, name: "Tuesday" },
    start_time: { _id: "dsbbrb3tgbba", index: 6, name: "13:30" },
  },
  {
    _id: "uaopdgduopbgv234",
    subject_name: "Software Engineering Testing",
    subject_code: "CMPE3008",
    session_type: "Lab",
    duration: "2",
    lecture_hall: "LT 105",
    lect_name: "Ms. Divya Nanayakkara",
    day: { _id: "fbdsfb4", index: 2, name: "Tuesday" },
    start_time: { _id: "fgilfugwr2tt", index: 8, name: "15:30" },
  },
  {
    _id: "vauodgvouegf298",
    subject_name: "Object Oriented Software Engineering",
    subject_code: "COMP2003",
    session_type: "Lab",
    duration: "2",
    lecture_hall: "LT 105",
    lect_name: "Ms. Divya Nanayakkara",
    day: { _id: "dsbfdfndf3", index: 3, name: "Wednesday" },
    start_time: { _id: "dguwod45zsz", index: 1, name: "08:30" },
  },
  {
    _id: "fpquogef824t029",
    subject_name: "Human Computer Interface",
    subject_code: "ISTE3002",
    session_type: "Lecture",
    duration: "2",
    lecture_hall: "LT 105",
    lect_name: "Mr. Jagath Wickramarathne",
    day: { _id: "dsbfdfndf3", index: 3, name: "Wednesday" },
    start_time: { _id: "xvzxxvzveg2", index: 3, name: "10:30" },
  },
  {
    _id: "divhdip08wrg20gh20r",
    subject_name: "Software Engineering Testing",
    subject_code: "CMPE3008",
    session_type: "Lecture",
    duration: "2",
    lecture_hall: "LT 105",
    lect_name: "Mr. Jeewaka Perera",
    day: { _id: "asasvadv2", index: 4, name: "Thursday" },
    start_time: { _id: "dsbbrb3tgbba", index: 6, name: "13:30" },
  },
  {
    _id: "dg4604ovoduvhv",
    subject_name: "Software Engineering Testing",
    subject_code: "CMPE3008",
    session_type: "Tute",
    duration: "1",
    lecture_hall: "LT 105",
    lect_name: "Mr. Jeewaka Perera",
    day: { _id: "asasvadv2", index: 4, name: "Thursday" },
    start_time: { _id: "fgilfugwr2tt", index: 8, name: "15:30" },
  },
  {
    _id: "dihwvpidvhw0pdgh208",
    subject_name: "Operating Systems",
    subject_code: "COMP2006",
    session_type: "Lecture",
    duration: "2",
    lecture_hall: "LT 105",
    lect_name: "Dr. Samantha Rajapaksha",
    day: { _id: "bsbfnt53ybf", index: 5, name: "Friday" },
    start_time: { _id: "dsbbrb3tgbba", index: 6, name: "13:30" },
  },
  {
    _id: "vadvbiadvp8o2ety",
    subject_name: "Operating Systems",
    subject_code: "COMP2006",
    session_type: "Tute",
    duration: "1",
    lecture_hall: "LT 105",
    lect_name: "Dr. Samantha Rajapaksha",
    day: { _id: "bsbfnt53ybf", index: 5, name: "Friday" },
    start_time: { _id: "fgilfugwr2tt", index: 8, name: "15:30" },
  },
];

export function getTimetableData() {
  return data;
}
